[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.8
padding.x = 10
padding.y = 10
dimensions.columns = 140
dimensions.lines = 77

[font]
normal.family = "Hack Nerd Font"
size = 11

[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "main"]

[scrolling]
history = 10000
