[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
padding.x = 10
padding.y = 10
dimensions.columns = 126
dimensions.lines = 71

[font]
normal.family = "Hack Nerd Font"
size = 12

[terminal.shell]
program = "/usr/bin/env"
args = ["zsh", "--login", "-c", "tmux new-session -A -s main"]

[scrolling]
history = 10000
