[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
dimensions.columns = 180
dimensions.lines = 55
option_as_alt = "both"

[font]
normal.family = "Hack Nerd Font"
size = 14

[terminal.shell]
program = "/usr/bin/env"
args = ["zsh", "--login", "-c", "tmux new-session -A -s main"]

[scrolling]
history = 10000

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
