#!/usr/bin/env zsh

# ##### Home Brew on MacOS #####
if [[ "$OS" == "darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# ##### Gnome #####
if [[ "$OS" == "linux" ]]; then
  gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
  gnome-extensions enable gTile@vibou
fi
