#!/usr/bin/env zsh

# ##### Locale #####
export TERM='rxvt-256color'

# ##### Set OS / Distro #####
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
DISTRO=unknow
ARCH=amd64
ARCHM=$(uname -m)

if [ "${OS}" = "linux" ]; then
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO=$ID
  else
    if [ -f /etc/gentoo-release ]; then
      DISTRO="gentoo"
    fi

    if [ -f /etc/SuSE-release ]; then
      DISTRO="suse"
    fi
  fi
fi

# ##### XDG Base Directory Specification #####
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$UID"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# ##### Zsh #####
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# ##### Editor #####
export EDITOR=vim
export VISUAL=vim

# ##### History #####
export HISTSIZE=5000
export HISTFILE="$ZDOTDIR/.zsh_history"
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# ##### Other settings #####
export LOCAL_BIN="$HOME/.local/bin"
export LIBVIRT_DEFAULT_URI="qemu:///system"
export AWS_PAGER=

# ##### Tmux #####
export TMUX_PLUGIN_MANAGER_PATH="$XDG_CONFIG_HOME/tmux/plugins"

# ##### Vim #####
export VIM_PACK="$XDG_CONFIG_HOME/vim/pack"
export VIM_THEMES="$VIM_PACK/themes/start"
export VIM_PLUGINS="$VIM_PACK/plugins/start"

# ##### Bat #####
export BAT_THEME="Visual Studio Dark+"

# ##### FZF #####
export FZF_DEFAULT_COMMAND='fd -H -E .git -E .cache'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd -t d -H -E .git -E .cache'
export FZF_DEFAULT_OPTS='
  --color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#262626
  --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
  --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
  --color=border:#262626,label:#aeaeae,query:#d9d9d9
  --border="bold" --border-label=""
  --preview-window="border-rounded,down:70%:wrap"
  --bind="ctrl-/:change-preview-window(hidden|)"
  --prompt="> " --marker=">" --pointer="◆" --separator="─" --scrollbar="│"
  --layout="reverse" --height="50%" --info="right" --multi --tmux=center,80%,50%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ directory ]] && eza --tree --color=always --icons {} || ([[ $(file --mime {}) =~ binary ]] && echo {} is binary file || bat -n --color=always -r :500 {})'
export FZF_CTRL_T_OPTS="--preview='$FZF_PREVIEW_COMMAND'"
export FZF_ALT_C_OPTS="--preview='eza --tree --color=always --icons {} | head -n 200'"

# ##### Go #####
export GOROOT="/usr/local/go"
export GOPATH="$XDG_CONFIG_HOME/go"

# ##### Path #####
export PATH="$LOCAL_BIN:$PATH"
export PATH="$XDG_CONFIG_HOME/tfenv/bin:$PATH"
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
