#!/usr/bin/env zsh

# ##### Locale #####
export TERM='rxvt-256color'

# ##### Set OS / Distro #####
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
OSS=$(uname -s)
DISTRO=unknow
ARCH=amd64
ARCHM=$(uname -m)

if [[ "$OS" = "linux" ]]; then
  if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    DISTRO=$ID
  else
    if [[ -f /etc/gentoo-release ]]; then
      DISTRO="gentoo"
    fi

    if [[ -f /etc/SuSE-release ]]; then
      DISTRO="suse"
    fi
  fi
fi

# ##### XDG Base Directory Specification #####
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# ##### Local Bin #####
export LOCAL_BIN="$HOME/.local/bin"

# ##### Zsh #####
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# ##### Editor #####
export EDITOR=vim
export VISUAL=vim

# ##### History #####
export HISTSIZE=5000
export HISTFILE="$ZDOTDIR/.zsh_history"
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# ##### Libvirt #####
if [[ "$DISTRO" == "fedora" ]]; then
  export LIBVIRT_DEFAULT_URI="qemu:///system"
fi

# ##### AWS #####
export AWS_PAGER=

# ##### Tmux #####
export TMUX_PLUGIN_MANAGER_PATH="$XDG_CONFIG_HOME/tmux/plugins"

# ##### Vim #####
if [[ "$OS" == "darwin" ]]; then
  export VIM_HOME="$HOME/.vim"
  export VIM_PACK="$VIM_HOME/pack"
  export VIM_THEMES="$VIM_PACK/themes/start"
  export VIM_PLUGINS="$VIM_PACK/plugins/start"
else
  export VIM_HOME="$XDG_CONFIG_HOME/vim"
  export VIM_PACK="$XDG_CONFIG_HOME/vim/pack"
  export VIM_THEMES="$VIM_PACK/themes/start"
  export VIM_PLUGINS="$VIM_PACK/plugins/start"
fi

# ##### Bat #####
export BAT_THEME="Visual Studio Dark+"

# ##### FZF #####
export FZF_DEFAULT_COMMAND='fd -E .git -E .cache -E .config -E .'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND -t d"
export FZF_DEFAULT_OPTS='
  --color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#262626
  --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
  --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
  --color=border:#262626,label:#aeaeae,query:#d9d9d9
  --border="bold" --border-label=""
  --preview-window="border-rounded,down:65%:wrap"
  --bind="ctrl-/:change-preview-window(hidden|)"
  --prompt="> " --marker=">" --pointer="◆" --separator="─" --scrollbar="│"
  --layout="reverse" --height="80%" --info="right" --multi --tmux=center,80%,50%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ directory ]] && eza --tree --level 1 --color=always --icons {} || ([[ $(file --mime {}) =~ binary ]] && echo {} is binary file || bat -n --color=always -r :500 {})'
export FZF_CTRL_T_OPTS="--preview='$FZF_PREVIEW_COMMAND'"
export FZF_ALT_C_OPTS="--preview='eza --tree --level 1 --color=always --icons {} | head -n 200'"

# ##### Go #####
export GOROOT="/usr/local/go"
export GOPATH="$XDG_CONFIG_HOME/go"

# ##### 1Password #####
if [[ "$OS" == "darwin" ]]; then
  export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

# ##### Terraform #####
export TENV_ROOT="$XDG_CONFIG_HOME/tenv"

# ##### Path #####
export PATH="$LOCAL_BIN:$PATH"
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
